name: Testing Composite

runs:
  using: "composite"
  steps:

    - uses: actions/setup-node@v6
      with:
        node-version: 22
    
    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Run lint
      run: npm run notlint
      shell: bash

    - name: Run tests
      run: npm run test
      shell: bash